export type TLanguageOption = {
  value: string; // ISO 639-1 code
  labelEN: string; // English name
  labelFR: string; // French name
  labelRU: string; // Russian name
};

export const allLanguagesOptions: TLanguageOption[] = [
  { value: 'aa', labelEN: 'Afar', labelFR: 'Afar', labelRU: 'Афар' },
  { value: 'ab', labelEN: 'Abkhazian', labelFR: 'Abkhaze', labelRU: 'Абхазский' },
  { value: 'ae', labelEN: 'Avestan', labelFR: 'Avestique', labelRU: 'Авестийский' },
  { value: 'af', labelEN: 'Afrikaans', labelFR: 'Afrikaans', labelRU: 'Африкаанс' },
  { value: 'ak', labelEN: 'Akan', labelFR: 'Akan', labelRU: 'Акан' },
  { value: 'am', labelEN: 'Amharic', labelFR: 'Amharique', labelRU: 'Амхарский' },
  { value: 'an', labelEN: 'Aragonese', labelFR: 'Aragonais', labelRU: 'Арагонский' },
  { value: 'ar', labelEN: 'Arabic', labelFR: 'Arabe', labelRU: 'Арабский' },
  { value: 'as', labelEN: 'Assamese', labelFR: 'Assamais', labelRU: 'Ассамский' },
  { value: 'av', labelEN: 'Avaric', labelFR: 'Avar', labelRU: 'Аварский' },
  { value: 'ay', labelEN: 'Aymara', labelFR: 'Aymara', labelRU: 'Аймара' },
  { value: 'az', labelEN: 'Azerbaijani', labelFR: 'Azéri', labelRU: 'Азербайджанский' },
  { value: 'ba', labelEN: 'Bashkir', labelFR: 'Bachkir', labelRU: 'Башкирский' },
  { value: 'be', labelEN: 'Belarusian', labelFR: 'Biélorusse', labelRU: 'Белорусский' },
  { value: 'bg', labelEN: 'Bulgarian', labelFR: 'Bulgare', labelRU: 'Болгарский' },
  { value: 'bh', labelEN: 'Bihari', labelFR: 'Bihari', labelRU: 'Бихарский' },
  { value: 'bi', labelEN: 'Bislama', labelFR: 'Bichlamar', labelRU: 'Бислама' },
  { value: 'bm', labelEN: 'Bambara', labelFR: 'Bambara', labelRU: 'Бамбара' },
  { value: 'bn', labelEN: 'Bengali', labelFR: 'Bengali', labelRU: 'Бенгальский' },
  { value: 'bo', labelEN: 'Tibetan', labelFR: 'Tibétain', labelRU: 'Тибетский' },
  { value: 'br', labelEN: 'Breton', labelFR: 'Breton', labelRU: 'Бретонский' },
  { value: 'bs', labelEN: 'Bosnian', labelFR: 'Bosniaque', labelRU: 'Боснийский' },
  { value: 'ca', labelEN: 'Catalan', labelFR: 'Catalan', labelRU: 'Каталанский' },
  { value: 'ce', labelEN: 'Chechen', labelFR: 'Tchétchène', labelRU: 'Чеченский' },
  { value: 'ch', labelEN: 'Chamorro', labelFR: 'Chamorro', labelRU: 'Чаморро' },
  { value: 'co', labelEN: 'Corsican', labelFR: 'Corse', labelRU: 'Корсиканский' },
  { value: 'cr', labelEN: 'Cree', labelFR: 'Cree', labelRU: 'Кри' },
  { value: 'cs', labelEN: 'Czech', labelFR: 'Tchèque', labelRU: 'Чешский' },
  {
    value: 'cu',
    labelEN: 'Church Slavic',
    labelFR: "Slavon d'église",
    labelRU: 'Церковнославянский',
  },
  { value: 'cv', labelEN: 'Chuvash', labelFR: 'Tchouvache', labelRU: 'Чувашский' },
  { value: 'cy', labelEN: 'Welsh', labelFR: 'Gallois', labelRU: 'Валлийский' },
  { value: 'da', labelEN: 'Danish', labelFR: 'Danois', labelRU: 'Датский' },
  { value: 'de', labelEN: 'German', labelFR: 'Allemand', labelRU: 'Немецкий' },
  { value: 'dv', labelEN: 'Divehi', labelFR: 'Maldivien', labelRU: 'Мальдивский' },
  { value: 'dz', labelEN: 'Dzongkha', labelFR: 'Dzongkha', labelRU: 'Дзонг-кэ' },
  { value: 'ee', labelEN: 'Ewe', labelFR: 'Éwé', labelRU: 'Эве' },
  { value: 'el', labelEN: 'Greek', labelFR: 'Grec', labelRU: 'Греческий' },
  { value: 'en', labelEN: 'English', labelFR: 'Anglais', labelRU: 'Английский' },
  { value: 'eo', labelEN: 'Esperanto', labelFR: 'Espéranto', labelRU: 'Эсперанто' },
  { value: 'es', labelEN: 'Spanish', labelFR: 'Espagnol', labelRU: 'Испанский' },
  { value: 'et', labelEN: 'Estonian', labelFR: 'Estonien', labelRU: 'Эстонский' },
  { value: 'eu', labelEN: 'Basque', labelFR: 'Basque', labelRU: 'Баскский' },
  { value: 'fa', labelEN: 'Persian', labelFR: 'Persan', labelRU: 'Персидский' },
  { value: 'ff', labelEN: 'Fulah', labelFR: 'Peul', labelRU: 'Фула' },
  { value: 'fi', labelEN: 'Finnish', labelFR: 'Finnois', labelRU: 'Финский' },
  { value: 'fj', labelEN: 'Fijian', labelFR: 'Fidjien', labelRU: 'Фиджийский' },
  { value: 'fo', labelEN: 'Faroese', labelFR: 'Féroïen', labelRU: 'Фарерский' },
  { value: 'fr', labelEN: 'French', labelFR: 'Français', labelRU: 'Французский' },
  {
    value: 'fy',
    labelEN: 'Western Frisian',
    labelFR: 'Frison occidental',
    labelRU: 'Западнофризский',
  },
  { value: 'ga', labelEN: 'Irish', labelFR: 'Irlandais', labelRU: 'Ирландский' },
  {
    value: 'gd',
    labelEN: 'Scottish Gaelic',
    labelFR: 'Gaélique écossais',
    labelRU: 'Шотландский гэльский',
  },
  { value: 'gl', labelEN: 'Galician', labelFR: 'Galicien', labelRU: 'Галисийский' },
  { value: 'gn', labelEN: 'Guarani', labelFR: 'Guarani', labelRU: 'Гуарани' },
  { value: 'gu', labelEN: 'Gujarati', labelFR: 'Gujarati', labelRU: 'Гуджарати' },
  { value: 'gv', labelEN: 'Manx', labelFR: 'Mannois', labelRU: 'Мэнский' },
  { value: 'ha', labelEN: 'Hausa', labelFR: 'Haoussa', labelRU: 'Хауса' },
  { value: 'he', labelEN: 'Hebrew', labelFR: 'Hébreu', labelRU: 'Иврит' },
  { value: 'hi', labelEN: 'Hindi', labelFR: 'Hindi', labelRU: 'Хинди' },
  { value: 'ho', labelEN: 'Hiri Motu', labelFR: 'Hiri Motu', labelRU: 'Хири моту' },
  { value: 'hr', labelEN: 'Croatian', labelFR: 'Croate', labelRU: 'Хорватский' },
  { value: 'ht', labelEN: 'Haitian', labelFR: 'Haïtien', labelRU: 'Гаитянский' },
  { value: 'hu', labelEN: 'Hungarian', labelFR: 'Hongrois', labelRU: 'Венгерский' },
  { value: 'hy', labelEN: 'Armenian', labelFR: 'Arménien', labelRU: 'Армянский' },
  { value: 'hz', labelEN: 'Herero', labelFR: 'Herero', labelRU: 'Гереро' },
  { value: 'ia', labelEN: 'Interlingua', labelFR: 'Interlingua', labelRU: 'Интерлингва' },
  { value: 'id', labelEN: 'Indonesian', labelFR: 'Indonésien', labelRU: 'Индонезийский' },
  { value: 'ie', labelEN: 'Interlingue', labelFR: 'Interlingue', labelRU: 'Интерлингве' },
  { value: 'ig', labelEN: 'Igbo', labelFR: 'Igbo', labelRU: 'Игбо' },
  { value: 'ii', labelEN: 'Sichuan Yi', labelFR: 'Yi du Sichuan', labelRU: 'Сычуаньский йи' },
  { value: 'ik', labelEN: 'Inupiaq', labelFR: 'Inupiaq', labelRU: 'Инупиак' },
  { value: 'io', labelEN: 'Ido', labelFR: 'Ido', labelRU: 'Идо' },
  { value: 'is', labelEN: 'Icelandic', labelFR: 'Islandais', labelRU: 'Исландский' },
  { value: 'it', labelEN: 'Italian', labelFR: 'Italien', labelRU: 'Итальянский' },
  { value: 'iu', labelEN: 'Inuktitut', labelFR: 'Inuktitut', labelRU: 'Инуктитут' },
  { value: 'ja', labelEN: 'Japanese', labelFR: 'Japonais', labelRU: 'Японский' },
  { value: 'jv', labelEN: 'Javanese', labelFR: 'Javanais', labelRU: 'Яванский' },
  { value: 'ka', labelEN: 'Georgian', labelFR: 'Géorgien', labelRU: 'Грузинский' },
  { value: 'kg', labelEN: 'Kongo', labelFR: 'Kongo', labelRU: 'Конго' },
  { value: 'ki', labelEN: 'Kikuyu', labelFR: 'Kikuyu', labelRU: 'Кикуйю' },
  { value: 'kj', labelEN: 'Kuanyama', labelFR: 'Kuanyama', labelRU: 'Куаньяма' },
  { value: 'kk', labelEN: 'Kazakh', labelFR: 'Kazakh', labelRU: 'Казахский' },
  { value: 'kl', labelEN: 'Kalaallisut', labelFR: 'Groenlandais', labelRU: 'Гренландский' },
  { value: 'km', labelEN: 'Central Khmer', labelFR: 'Khmer central', labelRU: 'Кхмерский' },
  { value: 'kn', labelEN: 'Kannada', labelFR: 'Kannada', labelRU: 'Каннада' },
  { value: 'ko', labelEN: 'Korean', labelFR: 'Coréen', labelRU: 'Корейский' },
  { value: 'kr', labelEN: 'Kanuri', labelFR: 'Kanouri', labelRU: 'Канури' },
  { value: 'ks', labelEN: 'Kashmiri', labelFR: 'Kashmiri', labelRU: 'Кашмирский' },
  { value: 'ku', labelEN: 'Kurdish', labelFR: 'Kurde', labelRU: 'Курдский' },
  { value: 'kv', labelEN: 'Komi', labelFR: 'Komi', labelRU: 'Коми' },
  { value: 'kw', labelEN: 'Cornish', labelFR: 'Cornique', labelRU: 'Корнский' },
  { value: 'ky', labelEN: 'Kirghiz', labelFR: 'Kirghiz', labelRU: 'Киргизский' },
  { value: 'la', labelEN: 'Latin', labelFR: 'Latin', labelRU: 'Латинский' },
  { value: 'lb', labelEN: 'Luxembourgish', labelFR: 'Luxembourgeois', labelRU: 'Люксембургский' },
  { value: 'lg', labelEN: 'Ganda', labelFR: 'Ganda', labelRU: 'Ганда' },
  { value: 'li', labelEN: 'Limburgan', labelFR: 'Limbourgeois', labelRU: 'Лимбургский' },
  { value: 'ln', labelEN: 'Lingala', labelFR: 'Lingala', labelRU: 'Лингала' },
  { value: 'lo', labelEN: 'Lao', labelFR: 'Lao', labelRU: 'Лаосский' },
  { value: 'lt', labelEN: 'Lithuanian', labelFR: 'Lituanien', labelRU: 'Литовский' },
  { value: 'lu', labelEN: 'Luba-Katanga', labelFR: 'Luba-Katanga', labelRU: 'Луба-катанга' },
  { value: 'lv', labelEN: 'Latvian', labelFR: 'Letton', labelRU: 'Латышский' },
  { value: 'mg', labelEN: 'Malagasy', labelFR: 'Malgache', labelRU: 'Малагасийский' },
  { value: 'mh', labelEN: 'Marshallese', labelFR: 'Marshallais', labelRU: 'Маршалльский' },
  { value: 'mi', labelEN: 'Maori', labelFR: 'Maori', labelRU: 'Маори' },
  { value: 'mk', labelEN: 'Macedonian', labelFR: 'Macédonien', labelRU: 'Македонский' },
  { value: 'ml', labelEN: 'Malayalam', labelFR: 'Malayalam', labelRU: 'Малаялам' },
  { value: 'mn', labelEN: 'Mongolian', labelFR: 'Mongol', labelRU: 'Монгольский' },
  { value: 'mr', labelEN: 'Marathi', labelFR: 'Marathi', labelRU: 'Маратхи' },
  { value: 'ms', labelEN: 'Malay', labelFR: 'Malais', labelRU: 'Малайский' },
  { value: 'mt', labelEN: 'Maltese', labelFR: 'Maltais', labelRU: 'Мальтийский' },
  { value: 'my', labelEN: 'Burmese', labelFR: 'Birman', labelRU: 'Бирманский' },
  { value: 'na', labelEN: 'Nauru', labelFR: 'Nauruan', labelRU: 'Науру' },
  {
    value: 'nb',
    labelEN: 'Norwegian Bokmål',
    labelFR: 'Norvégien Bokmål',
    labelRU: 'Норвежский Букмол',
  },
  {
    value: 'nd',
    labelEN: 'North Ndebele',
    labelFR: 'Ndébéle du Nord',
    labelRU: 'Северный ндебеле',
  },
  { value: 'ne', labelEN: 'Nepali', labelFR: 'Népalais', labelRU: 'Непальский' },
  { value: 'ng', labelEN: 'Ndonga', labelFR: 'Ndonga', labelRU: 'Ндонга' },
  { value: 'nl', labelEN: 'Dutch', labelFR: 'Néerlandais', labelRU: 'Голландский' },
  {
    value: 'nn',
    labelEN: 'Norwegian Nynorsk',
    labelFR: 'Norvégien Nynorsk',
    labelRU: 'Норвежский Нюнорск',
  },
  { value: 'no', labelEN: 'Norwegian', labelFR: 'Norvégien', labelRU: 'Норвежский' },
  { value: 'nr', labelEN: 'South Ndebele', labelFR: 'Ndébéle du Sud', labelRU: 'Южный ндебеле' },
  { value: 'nv', labelEN: 'Navajo', labelFR: 'Navajo', labelRU: 'Навахо' },
  { value: 'ny', labelEN: 'Chichewa', labelFR: 'Chichewa', labelRU: 'Чичева' },
  { value: 'oc', labelEN: 'Occitan', labelFR: 'Occitan', labelRU: 'Окситанский' },
  { value: 'oj', labelEN: 'Ojibwa', labelFR: 'Ojibwa', labelRU: 'Оджибве' },
  { value: 'om', labelEN: 'Oromo', labelFR: 'Oromo', labelRU: 'Оромо' },
  { value: 'or', labelEN: 'Oriya', labelFR: 'Oriya', labelRU: 'Ория' },
  { value: 'os', labelEN: 'Ossetian', labelFR: 'Ossète', labelRU: 'Осетинский' },
  { value: 'pa', labelEN: 'Punjabi', labelFR: 'Panjabi', labelRU: 'Панджаби' },
  { value: 'pi', labelEN: 'Pali', labelFR: 'Pali', labelRU: 'Пали' },
  { value: 'pl', labelEN: 'Polish', labelFR: 'Polonais', labelRU: 'Польский' },
  { value: 'ps', labelEN: 'Pashto', labelFR: 'Pachto', labelRU: 'Пушту' },
  { value: 'pt', labelEN: 'Portuguese', labelFR: 'Portugais', labelRU: 'Португальский' },
  { value: 'qu', labelEN: 'Quechua', labelFR: 'Quechua', labelRU: 'Кечуа' },
  { value: 'rm', labelEN: 'Romansh', labelFR: 'Romanche', labelRU: 'Ретороманский' },
  { value: 'rn', labelEN: 'Rundi', labelFR: 'Rundi', labelRU: 'Рунди' },
  { value: 'ro', labelEN: 'Romanian', labelFR: 'Roumain', labelRU: 'Румынский' },
  { value: 'ru', labelEN: 'Russian', labelFR: 'Russe', labelRU: 'Русский' },
  { value: 'rw', labelEN: 'Kinyarwanda', labelFR: 'Kinyarwanda', labelRU: 'Киньяруанда' },
  { value: 'sa', labelEN: 'Sanskrit', labelFR: 'Sanskrit', labelRU: 'Санскрит' },
  { value: 'sc', labelEN: 'Sardinian', labelFR: 'Sarde', labelRU: 'Сардинский' },
  { value: 'sd', labelEN: 'Sindhi', labelFR: 'Sindhi', labelRU: 'Синдхи' },
  { value: 'se', labelEN: 'Northern Sami', labelFR: 'Sami du Nord', labelRU: 'Северносаамский' },
  { value: 'sg', labelEN: 'Sango', labelFR: 'Sango', labelRU: 'Санго' },
  { value: 'si', labelEN: 'Sinhala', labelFR: 'Singhalais', labelRU: 'Сингальский' },
  { value: 'sk', labelEN: 'Slovak', labelFR: 'Slovaque', labelRU: 'Словацкий' },
  { value: 'sl', labelEN: 'Slovenian', labelFR: 'Slovène', labelRU: 'Словенский' },
  { value: 'sm', labelEN: 'Samoan', labelFR: 'Samoan', labelRU: 'Самоанский' },
  { value: 'sn', labelEN: 'Shona', labelFR: 'Shona', labelRU: 'Шона' },
  { value: 'so', labelEN: 'Somali', labelFR: 'Somali', labelRU: 'Сомалийский' },
  { value: 'sq', labelEN: 'Albanian', labelFR: 'Albanais', labelRU: 'Албанский' },
  { value: 'sr', labelEN: 'Serbian', labelFR: 'Serbe', labelRU: 'Сербский' },
  { value: 'ss', labelEN: 'Swati', labelFR: 'Swati', labelRU: 'Свати' },
  { value: 'st', labelEN: 'Southern Sotho', labelFR: 'Sotho du Sud', labelRU: 'Сесото' },
  { value: 'su', labelEN: 'Sundanese', labelFR: 'Soundanais', labelRU: 'Сунданский' },
  { value: 'sv', labelEN: 'Swedish', labelFR: 'Suédois', labelRU: 'Шведский' },
  { value: 'sw', labelEN: 'Swahili', labelFR: 'Swahili', labelRU: 'Суахили' },
  { value: 'ta', labelEN: 'Tamil', labelFR: 'Tamoul', labelRU: 'Тамильский' },
  { value: 'te', labelEN: 'Telugu', labelFR: 'Télougou', labelRU: 'Телугу' },
  { value: 'tg', labelEN: 'Tajik', labelFR: 'Tadjik', labelRU: 'Таджикский' },
  { value: 'th', labelEN: 'Thai', labelFR: 'Thaï', labelRU: 'Тайский' },
  { value: 'ti', labelEN: 'Tigrinya', labelFR: 'Tigrigna', labelRU: 'Тигринья' },
  { value: 'tk', labelEN: 'Turkmen', labelFR: 'Turkmène', labelRU: 'Туркменский' },
  { value: 'tl', labelEN: 'Tagalog', labelFR: 'Tagalog', labelRU: 'Тагальский' },
  { value: 'tn', labelEN: 'Tswana', labelFR: 'Tswana', labelRU: 'Тсвана' },
  { value: 'to', labelEN: 'Tonga', labelFR: 'Tonga', labelRU: 'Тонга' },
  { value: 'tr', labelEN: 'Turkish', labelFR: 'Turc', labelRU: 'Турецкий' },
  { value: 'ts', labelEN: 'Tsonga', labelFR: 'Tsonga', labelRU: 'Тсонга' },
  { value: 'tt', labelEN: 'Tatar', labelFR: 'Tatar', labelRU: 'Татарский' },
  { value: 'tw', labelEN: 'Twi', labelFR: 'Twi', labelRU: 'Тви' },
  { value: 'ty', labelEN: 'Tahitian', labelFR: 'Tahitien', labelRU: 'Таитянский' },
  { value: 'ug', labelEN: 'Uighur', labelFR: 'Ouïghour', labelRU: 'Уйгурский' },
  { value: 'uk', labelEN: 'Ukrainian', labelFR: 'Ukrainien', labelRU: 'Украинский' },
  { value: 'ur', labelEN: 'Urdu', labelFR: 'Ourdou', labelRU: 'Урду' },
  { value: 'uz', labelEN: 'Uzbek', labelFR: 'Ouzbek', labelRU: 'Узбекский' },
  { value: 've', labelEN: 'Venda', labelFR: 'Venda', labelRU: 'Венда' },
  { value: 'vi', labelEN: 'Vietnamese', labelFR: 'Vietnamien', labelRU: 'Вьетнамский' },
  { value: 'vo', labelEN: 'Volapük', labelFR: 'Volapük', labelRU: 'Волапюк' },
  { value: 'wa', labelEN: 'Walloon', labelFR: 'Wallon', labelRU: 'Валлонский' },
  { value: 'wo', labelEN: 'Wolof', labelFR: 'Wolof', labelRU: 'Волоф' },
  { value: 'xh', labelEN: 'Xhosa', labelFR: 'Xhosa', labelRU: 'Коса' },
  { value: 'yi', labelEN: 'Yiddish', labelFR: 'Yiddish', labelRU: 'Идиш' },
  { value: 'yo', labelEN: 'Yoruba', labelFR: 'Yoruba', labelRU: 'Йоруба' },
  { value: 'za', labelEN: 'Zhuang', labelFR: 'Zhuang', labelRU: 'Чжуанский' },
  { value: 'zh', labelEN: 'Chinese', labelFR: 'Chinois', labelRU: 'Китайский' },
  { value: 'zu', labelEN: 'Zulu', labelFR: 'Zoulou', labelRU: 'Зулу' },
];
