import { capitalize } from '@/utils/format-string';

// Define the structure for language option
type LanguageOption = {
  value: string; // ISO2 country code
  label: string; // Language name in the respective language
};

// Language options with labels in English
const popularLanguagesOptionsEN: LanguageOption[] = [
  { value: 'AL', label: 'Albanian' },
  { value: 'EG', label: 'Arabic' },
  { value: 'BD', label: 'Bengali' },
  { value: 'BG', label: 'Bulgarian' },
  { value: 'CN', label: 'Chinese' },
  { value: 'HR', label: 'Croatian' },
  { value: 'CZ', label: 'Czech' },
  { value: 'DK', label: 'Danish' },
  { value: 'NL', label: 'Dutch' },
  { value: 'EN', label: 'English' },
  { value: 'EE', label: 'Estonian' },
  { value: 'FI', label: 'Finnish' },
  { value: 'FR', label: 'French' },
  { value: 'DE', label: 'German' },
  { value: 'GR', label: 'Greek' },
  { value: 'IL', label: 'Hebrew' },
  { value: 'IN', label: 'Hindi' },
  { value: 'HU', label: 'Hungarian' },
  { value: 'IS', label: 'Icelandic' },
  { value: 'ID', label: 'Indonesian' },
  { value: 'IT', label: 'Italian' },
  { value: 'JP', label: 'Japanese' },
  { value: 'KR', label: 'Korean' },
  { value: 'LV', label: 'Latvian' },
  { value: 'LT', label: 'Lithuanian' },
  { value: 'MY', label: 'Malay' },
  { value: 'NO', label: 'Norwegian' },
  { value: 'IR', label: 'Persian' },
  { value: 'PL', label: 'Polish' },
  { value: 'PT', label: 'Portuguese' },
  { value: 'RO', label: 'Romanian' },
  { value: 'RU', label: 'Russian' },
  { value: 'RS', label: 'Serbian' },
  { value: 'SK', label: 'Slovak' },
  { value: 'SI', label: 'Slovenian' },
  { value: 'ES', label: 'Spanish' },
  { value: 'SE', label: 'Swedish' },
  { value: 'TH', label: 'Thai' },
  { value: 'TR', label: 'Turkish' },
  { value: 'UA', label: 'Ukrainian' },
  { value: 'VN', label: 'Vietnamese' },
  { value: 'PH', label: 'Filipino' },
];

// Language options with labels in French
const popularLanguagesOptionsFR: LanguageOption[] = [
  { value: 'AL', label: 'Albanais' },
  { value: 'EN', label: 'Anglais' },
  { value: 'DE', label: 'Allemand' },
  { value: 'EG', label: 'Arabe' },
  { value: 'BD', label: 'Bengali' },
  { value: 'BG', label: 'Bulgare' },
  { value: 'CN', label: 'Chinois' },
  { value: 'HR', label: 'Croate' },
  { value: 'DK', label: 'Danois' },
  { value: 'EE', label: 'Estonien' },
  { value: 'ES', label: 'Espagnol' },
  { value: 'FI', label: 'Finnois' },
  { value: 'PH', label: 'Filipino' },
  { value: 'FR', label: 'Français' },
  { value: 'GR', label: 'Grec' },
  { value: 'IL', label: 'Hébreu' },
  { value: 'IN', label: 'Hindi' },
  { value: 'HU', label: 'Hongrois' },
  { value: 'ID', label: 'Indonésien' },
  { value: 'IS', label: 'Islandais' },
  { value: 'IT', label: 'Italien' },
  { value: 'JP', label: 'Japonais' },
  { value: 'KR', label: 'Coréen' },
  { value: 'LV', label: 'Letton' },
  { value: 'LT', label: 'Lituanien' },
  { value: 'MY', label: 'Malais' },
  { value: 'NL', label: 'Néerlandais' },
  { value: 'NO', label: 'Norvégien' },
  { value: 'IR', label: 'Persan' },
  { value: 'PL', label: 'Polonais' },
  { value: 'PT', label: 'Portugais' },
  { value: 'RO', label: 'Roumain' },
  { value: 'RU', label: 'Russe' },
  { value: 'RS', label: 'Serbe' },
  { value: 'SK', label: 'Slovaque' },
  { value: 'SI', label: 'Slovène' },
  { value: 'SE', label: 'Suédois' },
  { value: 'CZ', label: 'Tchèque' },
  { value: 'TH', label: 'Thaï' },
  { value: 'TR', label: 'Turc' },
  { value: 'UA', label: 'Ukrainien' },
  { value: 'VN', label: 'Vietnamien' },
];

// Language options with labels in Russian
const popularLanguagesOptionsRU: LanguageOption[] = [
  { value: 'AL', label: 'Албанский' },
  { value: 'EN', label: 'Английский' },
  { value: 'EG', label: 'Арабский' },
  { value: 'BD', label: 'Бенгальский' },
  { value: 'BG', label: 'Болгарский' },
  { value: 'VN', label: 'Вьетнамский' },
  { value: 'GR', label: 'Греческий' },
  { value: 'NL', label: 'Голландский' },
  { value: 'DK', label: 'Датский' },
  { value: 'DE', label: 'Немецкий' },
  { value: 'EE', label: 'Эстонский' },
  { value: 'ES', label: 'Испанский' },
  { value: 'IL', label: 'Иврит' },
  { value: 'IN', label: 'Хинди' },
  { value: 'ID', label: 'Индонезийский' },
  { value: 'IS', label: 'Исландский' },
  { value: 'IT', label: 'Итальянский' },
  { value: 'CN', label: 'Китайский' },
  { value: 'KR', label: 'Корейский' },
  { value: 'LV', label: 'Латышский' },
  { value: 'LT', label: 'Литовский' },
  { value: 'MY', label: 'Малайский' },
  { value: 'NO', label: 'Норвежский' },
  { value: 'IR', label: 'Персидский' },
  { value: 'PL', label: 'Польский' },
  { value: 'PT', label: 'Португальский' },
  { value: 'RO', label: 'Румынский' },
  { value: 'RU', label: 'Русский' },
  { value: 'RS', label: 'Сербский' },
  { value: 'SK', label: 'Словацкий' },
  { value: 'SI', label: 'Словенский' },
  { value: 'UA', label: 'Украинский' },
  { value: 'FI', label: 'Финский' },
  { value: 'PH', label: 'Филиппинский' },
  { value: 'FR', label: 'Французский' },
  { value: 'HR', label: 'Хорватский' },
  { value: 'CZ', label: 'Чешский' },
  { value: 'SE', label: 'Шведский' },
  { value: 'JP', label: 'Японский' },
  { value: 'HU', label: 'Венгерский' },
  { value: 'TH', label: 'Тайский' },
  { value: 'TR', label: 'Турецкий' },
];

export const getFlag = (langName: string, locale: 'en' | 'fr' | 'ru') => {
  const options =
    locale === 'en'
      ? popularLanguagesOptionsEN
      : locale === 'fr'
        ? popularLanguagesOptionsFR
        : popularLanguagesOptionsRU;
  return options.find(({ label }) => label === capitalize(langName))?.value ?? 'europe';
};
